### ISSUE TITLE
column names as "EntrezGeneSymbol" 

### ISSUE THREAD

**Issue by foocheung2** [SomaLogic/SomaDataIO#1]
Hi

I see the output of "read_adat" generates "SeqId" columns ids, is there an function to convert the column names to having the corresponding "EntrezGeneSymbol" 

Thanks in advance for the Package and your time.

Thanks
Foo

**Comment by stufield** [comment]
Thanks @foocheung2 for submitting this issue.

Previous versions of `SomaDataIO` (`< v5.0`) used a combination of `EntrezGeneSymbol` + `SeqId` to build unique column IDs.  While this has the advantage of human readable, there are several disadvantages, and thus we no longer recommend performing analyses using `EntrezGeneSymbols` as IDs.

1. Our database relating `EntrezGeneSymbols` -> `SOMAmer` reagents is periodically updated and curated. As a consequence, there is no guarantee they will be stable across analyses. However, the `SeqId` *is* unique and stable (within a specific menu/version of our assay). Thus we have opted for the `seq.XXXX.XX` format you see in the current `soma_adat` object.
2. As a proteomics company, we feel it is important to emphasize that our analytes have been generated to bind specific *protein targets*, not the genes that encode them. Thus we have moved away from using `EntrezGeneSymbols` as column identifiers.

However, there are options ...

The function `getFeatureData()` interrogates the `soma_adat` object and pulls the feature annotation meta data contained in the attributes of the object (the `Col.Meta`). This table contains the specific column `AptName` (col `1L`) which represents the unique key between this annotations table and the column names of the `soma_adat` from which it came.

From this lookup-table, you can now map `EntrezGeneSymbols` to `SeqIds`. For example:

```r
lookup <- getFeatureData(example_data)            # create lookup table
feats  <- sample(getFeatures(example_data), 5)    # 5 random feature columns
dplyr::filter(lookup, AptName %in% feats)
```

You could even use the lookup table to re-map the column names with `EntrezGeneSymbols` if you wanted. But as I mentioned above, we do not recommend this, nor can you rely non these names to be stable in the long-term.

Hope this helps

**Comment by foocheung2** [comment]
Thank @stufield for your answer.

Very helpful.

Best

Foo
