### ISSUE TITLE
write_adat() error

### ISSUE THREAD

**Issue by lzy604** [SomaLogic/SomaDataIO#135]
write_adat(adat_out, file = tempfile(fileext = ".adat"))
Error in ui_bullet(x, crayon::green(cli::symbol$tick)): could not find function "ui_bullet"

**Comment by scheidec** [comment]
Hi @lzy604. This is a duplicate of #129, and was fixed in #130.  This bug fix will soon be incorporated into a CRAN release, but in the meantime, to resolve this issue, please install the development version of the package via 

```
remotes::install_github("SomaLogic/SomaDataIO")
```

**Comment by MiquelTriana** [comment]
Hi, when will the next release to CRAN be? I need this bug to be solved, and be able to install from CRAN (due to compliance in my company)

**Comment by scheidec** [comment]
> Hi, when will the next release to CRAN be? I need this bug to be solved, and be able to install from CRAN (due to compliance in my company)

Hi @MiquelTriana. We are planning for a CRAN release sometime this month, which will include this bug fix. Thanks!

**Comment by scheidec** [comment]
> Hi, when will the next release to CRAN be? I need this bug to be solved, and be able to install from CRAN (due to compliance in my company)

v6.2.0 is now released on CRAN.
