### ISSUE TITLE
Unable to write out .adat file 

### ISSUE THREAD

**Issue by bbodek** [SomaLogic/SomaDataIO#15]
Hi,

When trying to write an adat file out, I am receiving the error
```
x Attributes has only 3 entries: 'names', 'row.names', 'class'
 Error in mutate.soma_adat(x, blank_col = NA_character_) : 
is.intact.attributes(.data) is not TRUE
```

I am using the following code to try to write out the file:
```
if(!is.intact.attributes(filtered_adat)){
  print("Error: file format is not correct to produce a filtered .adat file")
} else if(is.intact.attributes(filtered_adat)){
  write_adat(filtered_adat, file = filtered_adat_output) 
} 
```

When I run `is.intact.attribubes(filtered_adat)` it returns "TRUE", so I am not sure what is going wrong in the write_adat step.

Thanks!

**Comment by bbodek** [comment]
To add to this, I get this issue even when reading in an adat file and trying to write it back out with no changes, so it does not appear to be caused by any changes I make to the adat file.

**Comment by bbodek** [comment]
You're right, I was using dplyr v1.0.8. I reverted back to v1.0.6 and all seems to work now. 

Thank you!

**Comment by stufield** [comment]
Re-opening this issue for better visibility (see #16), until the next release where this issue will be solved.
