### ISSUE TITLE
SomaDataIO on CRAN / Bioconductor

### ISSUE THREAD

**Issue by lassemaretty** [SomaLogic/SomaDataIO#20]
Hi,

We are working on an R package for performing analyses of SomaLogic data and use the SomaLogicIO package to read .adat files etc. As we want to submit our package to CRAN, it seems we also need any dependencies to be on CRAN or Bioconductor. Hence, we currently need to copy the necessary SomaDataIO files into our repository, but it would be more clean and future proof to be able to depend directly on your package.

Do you have any plans for submitting your package to any of these repositories? 

Best regards,

Lasse Maretty

**Comment by lassemaretty** [comment]
Hi @stufield,

Sorry for my late reply - I was on holiday:)

Sounds great if you are considering putting it on CRAN, we would really appreciate that. Please let me know of any developments in this direction.

Thanks! Best,
Lasse

**Comment by stufield** [comment]
Hi @lassemaretty ,

Good news! The plan is to eventually submit to `CRAN`, which would enable you to submit your package to `CRAN` with a `SomaDataIO` dependency. However, I the timeline for this may be limiting. There are still remaining issues that would need to be ironed out before we can finalize a submission to `CRAN`, e.g. marketing, branding, re-naming, etc. (there is a possibility that `SomaDataIO` will be renamed as part of a broader branding exercise at SomaLogic). My best estimate for a `CRAN` submission is the 1-3 month time frame.

If this fits within your time limitations, fantastic. If not, it might be possible to "borrow" our code internally under the `MIT` license until `SomaDataIO` is officially on `CRAN`. This would enable you to move forward with your package, and only require a small refactoring to add the dependency once `SomaDataIO` is available on `CRAN`. If you go this route, I would be happy to help if you let me know which part of `SomaDataIO` you depend upon.

Cheers,
Stu

**Comment by lassemaretty** [comment]
Hi @stufield 

Sounds great that you are planning on a CRAN submission. It would enable us to create a nice ecosystem around SomaLogic data.
Timeframe is not critical as we have now adopted a workaround that will do for now. 

I look forward to seeing it on CRAN. Please post here once it is there.

Thanks again,

Lasse

**Comment by lassemaretty** [comment]
Hi @stufield 

Just kindly curious about whether there has been any progress towards a CRAN or bioconductor submission?

Best,

Lasse

**Comment by stufield** [comment]
Hi @lassemaretty ,

We've targeted CRAN submission for an end Jan - early Feb 2023 timeframe. I'll be working with the marketing team in the coming weeks to finalize a possible name change of the package to align with our other open source software offerings. So please be aware of that ... new branding, new name, new `v 1.0.0` versioning, etc. All those decisions are the major roadblocks at the moment. Once they're clear, I imagine a submission and acceptance will be relatively straightforward.

Thanks!
Stu

**Comment by lassemaretty** [comment]
Hi Stu,

Thank you for your response! Great to hear that this is still in the making. I look forward to seeing it on CRAN!

Best,

Lasse

**Comment by stufield** [comment]
Submitted to CRAN 🤞🏽 
- it will keep the same package name `SomaDataIO`
- continued versioning, bump to `v6.0.0` for CRAN
- hopefully soon!

**Comment by stufield** [comment]
Accepted and published!

https://cran.r-project.org/web/packages/SomaDataIO/index.html

**Comment by lassemaretty** [comment]
Congrats! Thank you for this effort.

Best,

Lasse


tir. 21. mar. 2023 kl. 18.12 skrev Stu Field ***@***.***>:
