### ISSUE TITLE
Loading an adat

### ISSUE THREAD

**Issue by MoemenEltobgy** [SomaLogic/SomaDataIO#27]
I have been trying to load an adat file in R studio but every time I get this error message:
> f <- system.file("~/Downloads","anmlSMP.adat", package = "SomaDataIO", mustWork = TRUE)
Error in system.file("~/Downloads", "anmlSMP.adat", package = "SomaDataIO",  : 
  no file found

However, when I try to load the example adat file, it works. I tried to change the directory or the file name but still stuck with the same issue. The file can be loaded by load a file feature of r studio, but I do not know how to proceed from there without using the read_adat.

any help would be much appreciated as soon as possible!

thanks

**Comment by stufield** [comment]
Try passing the file path directly to `read_adat()`.

The `system.file()` call is reserved to package files included with `SomaDataIO` (`"anmlSMP.adat"` is not part of `SomaDataIO`).

The only `*.adat` files (2) that are included in `SomaDataIO` are:

```r
 dir(system.file("example", package = "SomaDataIO"))
```

For your purpose, it looks like you're trying to load a local `*.adat` file, so providing a direct path to the file will accomplish that:

```r
read_adat("~/Downloads/anmlSMP.adat")
```

**Comment by MoemenEltobgy** [comment]
It worked. Thank you. I really appreciate it. Actually, I am new to R and this was driving me crazy.
