### ISSUE TITLE
Volcano plot

### ISSUE THREAD

**Issue by MoemenEltobgy** [SomaLogic/SomaDataIO#30]
I know I have been asking a lot. Sorry for that.
I need to do a volcano plot so I need the log2 fold change. How can I edit this code to be able to get the log2 fold change with the t test? or Is there another way to do it?

t_tests <- t_tests %>% 
  mutate(
    formula = map(AptName, ~ as.formula(paste(.x, "~ Sex"))), # create formula
    t_test  = map(formula, ~ stats::t.test(.x, data = cleanData)),  # fit t-tests
    t_stat  = map_dbl(t_test, "statistic"),            # pull out t-statistic
    p.value = map_dbl(t_test, "p.value"),              # pull out p-values
    fdr     = p.adjust(p.value, method = "BH")         # FDR for multiple testing
  ) %>%
  arrange(p.value) %>%           # re-order by `p-value`
  mutate(rank = row_number())    # add numeric ranks

thanks.

**Comment by stufield** [comment]
Forwarded on to techsupport@somalogic.com
@wschwarzmann
