### ISSUE TITLE
Error when using read_adat() + issue in setup script

### ISSUE THREAD

**Issue by Hijinx725** [SomaLogic/SomaDataIO#40]
## Checks
- [ ] Please search previous issues before creating a new one,
  to ensure yours is not a duplicate. You can
  [edit the qualifiers](https://help.github.com/articles/searching-issues-and-pull-requests/),
  `is:pr`, `is:closed`, etc., as needed, e.g. you'd simply remove `is:open` to
  search _all_ issues in the repo, open or closed.
- [ ] Please include a minimal reproducible example (AKA a `reprex`)

If you've never heard of a [reprex](http://reprex.tidyverse.org/) before,
please start by reading <https://www.tidyverse.org/help/#reprex>.

---

## Description
Please briefly describe the problem you have encountered
and what output you expected ...

I tired this code from the readme: 

f <- system.file("extdata", "example_data10.adat",
                 package = "SomaDataIO", mustWork = TRUE)
my_adat <- read_adat(f)
is.soma_adat(my_adat)
my_adat

Also, in /data_raw/SomaScanObjects.R there is a missing ')' in the second function.

## Output
```r
Error in gsub_(st$close, st$open, text, fixed = TRUE, useBytes = TRUE) : 
  could not find function "gsub_"
In addition: Warning message:
In is_string(left) : restarting interrupted promise evaluation
```

## Expected Output
```r
table
```

## Steps
Please describe any steps you have already taken that may
assist in reproducing the (unexpected) behavior:

- installed SomaDataIO from R ( version 4.1.2 )
- installed missing required packages listed in readme

## Priority Level
- [ ] High
- [x] Medium
- [ ] Low

---

Thanks for reporting :partying_face:!

**Comment by stufield** [comment]
Hi @Hijinx725 ,

- unfortunately I am unable to reproduce the error you are experiencing. Could you please generate a proper `reprex` that reproduces the error? Specifically, which version of `SomaDataIO` you are using (`v6.0.0`?)
- the `SomaScanObjects.R` script is meant for updating package objects only, and  is not intended for end user interaction (see `.Rbuildignore`). However, thank you for the catch, I will fix in an upcoming PR.

Thank you!
