### ISSUE TITLE
Read adat file < v4.0

### ISSUE THREAD

**Issue by andreagrioni** [SomaLogic/SomaDataIO#9]
Hi,

Thank you for maintaining such useful tool. I was wondering if it is possible to read older version of SomaScan ADAT file, e.g. form version v.3.

Thank you,
kind regards

**Comment by andreagrioni** [comment]
Hi, thank you for the detailed answer! here is the error returned by `SomaDataIO::read_adat()` : 

`Error in parseHeader(file) : object 'section' not found`

I cannot provide a repex due to company policy, but the first line of the ADAT file is `SeqId`, while the section `^HEADER` and its content is missed. As the file was truncated at the origin, is there a possibility of forcing `SomaDataIO::read_adat()` to load the ADAT file even if the header section is missed?

Thank you for your help.

**Comment by stufield** [comment]
Unfortunately no. I wouldn't recommend it for 2 reasons:

1. the ADAT has clearly been modified from its original source, and you have no way of knowing what else may have been modified.
2. the downstream tools provided in SomaDataIO depend heavily on the Header attribute information (many of the `tidyverse` S3 methods will be rendered non-functional.

If obtaining the original ADAT file is not possible, you *could* try to hack what `read_adat()` is doing under the hood. But there are many checks that occur to ensure the integrity of the data that you would be lacking. So again, if you are conducting a production level analysis, or in a regulated environment, __I do not recommend__ working around `read_adat()`.

Below is untested pseudo-code:

1. read-in the main data matrix (table) via `data <- read.delim(file, skip = x)` where `x` is how many lines until the data starts
2. get the Analyte Info (we call it Col.Meta):
```
# `n` is how long many lines the column meta data section is above the table
cm <- as_tibble(readLines(file, n = n)
names(cm) <- unname(sapply(cm, `[[`, i = 1L))   # you may have to do these 2 steps depending
cm <- cm[-1L, ]
```
3. covert the SeqIds to `soma_adat` apt-names:  `apt_names <- seqid2apt(cm$SeqId)`
4. replace appropriate entries of the names of the data table with your constructed `seq.1234.56` names (but mind not to overwrite the leading elements you want to keep; non-analyte columns)
5. You will also need to dummy up some `Header.Meta` for that attributes, but this is less critical.
```
HM <- list(HEADER   = list(Version = "1.2", Title = "SL-99-999"),
           COL_DATA = list(Name = "SeqId", Type = "String"),
           ROW_DATA = list(Name = "PlateId", Type = "String"))
```
6. adjust the attributes: 
```
structure(data, names = apt_names, Col.Meta = cm, Header.Meta = HM, class = c("soma_adat", "data.frame"))
```
7.  your goal should be to work through the steps until `is.intact.attributes(data)` returns `TRUE`.

Once again, the above is simply pseudo-code (may need to be adjusted), and if your analysis needs to be reproducible and in a regulated environment, I wouldn't recommend this implementation. It is always best to get the original source ADAT file and allow `read_adat()` to perform its internal checks.
